version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mkulik/testtask:testtask
    depends_on:
      - redis
    ports:
      - "9000:9000"
    networks:
      - default